apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ollama-home-ipex
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/muflo/Volume10TB/ollama-ipex"
