apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: llm
  name: pv-ollama-home-ipex
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
